murders <- read.csv("murders.csv")
str(murders)
statesMap <- map_data("state")
str(statesMap)
library(ggplot2)
ggplot(statesMap, aes(long, lat, group=group)) + geom_polygon(fill="white", color="black")
murders$region <- tolower(murders$State)
murdersMap <- merge(statesMap, murders, by="region")
str(murdersMap)
ggplot(murdersMap, aes(x=long, y=lat, group=group, fill=Population)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
murdersMap$MurderRate <- murdersMap$Murders/murdersMap$Population*100000
ggplot(murdersMap, aes(x=long, y=lat, group=group, fill=MurderRate)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
ggplot(murdersMap, aes(x=long, y=lat, group=group, fill=MurderRate)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend", limits=c(0,10))
ggplot(murdersMap, aes(x=long, y=lat, group=group, fill=GunOwnership)) + geom_polygon(color="black") + scale_fill_gradient(low="black", high="red", guide="legend")
