who <- read.csv("WHO.csv")
str(who)
library(ggplot2)
plot(who$GNI, who$FertilityRate)
attach(who)
scatter <- ggplot(who, aes(x = GNI, y = FertilityRate))
fertilityGNIPlot <- scatter + geom_point(color="darkred", size=3, shape=3) + ggtitle("Fertility Rate vs Gross National Income")
pdf("MyPlot.pdf")
print(fertilityGNIPlot)
dev.off()
ggplot(who, aes(x = GNI, y = FertilityRate, color = Region)) + geom_point() 
ggplot(who, aes(x = GNI, y = FertilityRate, color = LifeExpectancy)) + geom_point() 
ggplot(who, aes(x = FertilityRate, y = Under15)) + geom_point()
ggplot(who, aes(x = log(FertilityRate), y = Under15)) + geom_point()
model <- lm(Under15 ~ FertilityRate, data = who)
summary(model)
ggplot(who, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = "lm")
ggplot(who, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = "lm", level = 0.99)
ggplot(who, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = "lm", se = FALSE)
ggplot(who, aes(x = log(FertilityRate), y = Under15)) + geom_point() + stat_smooth(method = "lm", se = FALSE, color = "red")
ggplot(who, aes(x = log(FertilityRate), y = Under15, color = Region)) + geom_point() + scale_color_brewer(palette="Dark2")
